import type { Metadata } from 'next';

import { Providers } from '@/components/providers';

export const metadata: Metadata = {
  title: 'Capputeeno',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang='en'>
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    </>
  );
}
